FROM python:3.7

LABEL name="custodian" \
      description="Cloud Management Rules Engine" \
      repository="http://github.com/cloud-custodian/cloud-custodian" \
      homepage="http://github.com/cloud-custodian/cloud-custodian" \
      maintainer="Custodian Community <https://cloudcustodian.io>"

# Install tools
COPY tools/ /src/tools/
RUN cd /src/tools/c7n_azure && pip3 install -r requirements.txt -e . \
  && cd /src/tools/c7n_gcp && pip3 install -r requirements.txt -e . \
  && cd /src/tools/c7n_mailer && pip3 install -r requirements.txt -e . \
  && cd /src/tools/c7n_kube && pip3 install -r requirements.txt -e .

# Install requirements
ADD . /src
WORKDIR /src
RUN pip3 install -r requirements.txt -e .

# Setup for EntryPoint
ENV LC_ALL="C.UTF-8" LANG="C.UTF-8"
#VOLUME ["/var/log/cloud-custodian", "/etc/cloud-custodian"]
#ENTRYPOINT ["/usr/local/bin/custodian"]

#RUN pip3 install tox && tox -e py37
